apiVersion: apps/v1
kind: Deployment
metadata:
  name: doctor-service
  labels:
    app: doctor-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: doctor-service
  template:
    metadata:
      labels:
        app: doctor-service
    spec:
      containers:
      - name: doctor-service
        image: primehealth/doctor-service:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5002
        env:
        - name: PORT
          value: "5002"
        - name: MONGODB_URI
          valueFrom:
            configMapKeyRef:
              name: primehealth-config
              key: MONGODB_URI_DOCTOR
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: primehealth-secrets
              key: JWT_SECRET

---
apiVersion: v1
kind: Service
metadata:
  name: doctor-service
spec:
  selector:
    app: doctor-service
  ports:
    - protocol: TCP
      port: 5002
      targetPort: 5002
  type: ClusterIP
