apiVersion: v1
kind: Service
metadata:
  name: appointment-service
  labels:
    app: appointment-service
spec:
  type: ClusterIP
  selector:
    app: appointment-service
  ports:
    - port: 5003
      targetPort: 5003
      protocol: TCP
