apiVersion: v1
kind: ConfigMap
metadata:
  name: primehealth-config
  namespace: default
data:
  NODE_ENV: "production"
  CORS_ORIGIN: "http://localhost:3000"
  DOCTOR_SERVICE_URL: "http://doctor-service:5002"
  APPOINTMENT_SERVICE_URL: "http://appointment-service:5003"
  PAYMENT_SERVICE_URL: "http://payment-service:5004"
  PRESCRIPTION_SERVICE_URL: "http://prescription-service:5005"
